/*
 * generated by Xtext 2.28.0
 */
package ardsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractArdslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://ontologicals/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://graphics/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://physics/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://gameloop/1.0"));
		return result;
	}
}
