/*
 * generated by Xtext 2.28.0
 */
package ardsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArdslUiModule extends AbstractArdslUiModule {

	public ArdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
