/*
 * generated by Xtext 2.28.0
 */
package ardsl.parser.antlr;

import ardsl.parser.antlr.internal.InternalArdslParser;
import ardsl.services.ArdslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ArdslParser extends AbstractAntlrParser {

	@Inject
	private ArdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArdslParser createParser(XtextTokenStream stream) {
		return new InternalArdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Ontological";
	}

	public ArdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
