/*
 * generated by Xtext 2.28.0
 */
package arg;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArgRuntimeModule extends AbstractArgRuntimeModule {
}
