/*
 * generated by Xtext 2.28.0
 */
package ardsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArdslStandaloneSetup extends ArdslStandaloneSetupGenerated {

	public static void doSetup() {
		new ArdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
