/*
 * generated by Xtext 2.28.0
 */
package ardsl.ui.tests;

import ardsl.editor.ui.internal.EditorActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ArdslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("ardsl.Ardsl");
	}

}
