/*
 * generated by Xtext 2.28.0
 */
package ardsl.ide;

import ardsl.ArdslRuntimeModule;
import ardsl.ArdslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ArdslIdeSetup extends ArdslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArdslRuntimeModule(), new ArdslIdeModule()));
	}
	
}
