/*
 * generated by Xtext 2.28.0
 */
package ardsl.ide.contentassist.antlr;

import ardsl.ide.contentassist.antlr.internal.InternalArdslParser;
import ardsl.services.ArdslGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ArdslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ArdslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ArdslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getLogicOpAccess().getAlternatives(), "rule__LogicOp__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getBasicActionsAccess().getAlternatives(), "rule__BasicActions__Alternatives");
			builder.put(grammarAccess.getPlanesAccess().getAlternatives(), "rule__Planes__Alternatives");
			builder.put(grammarAccess.getBodyTypeAccess().getAlternatives(), "rule__BodyType__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
			builder.put(grammarAccess.getLogicOpsAccess().getAlternatives(), "rule__LogicOps__Alternatives");
			builder.put(grammarAccess.getArithmOpsAccess().getAlternatives(), "rule__ArithmOps__Alternatives");
			builder.put(grammarAccess.getOntologicalAccess().getGroup(), "rule__Ontological__Group__0");
			builder.put(grammarAccess.getOntologicalAccess().getGroup_3(), "rule__Ontological__Group_3__0");
			builder.put(grammarAccess.getOntologicalAccess().getGroup_7(), "rule__Ontological__Group_7__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup_2(), "rule__Class__Group_2__0");
			builder.put(grammarAccess.getClassAccess().getGroup_2_1(), "rule__Class__Group_2_1__0");
			builder.put(grammarAccess.getClassAccess().getGroup_3(), "rule__Class__Group_3__0");
			builder.put(grammarAccess.getClassAccess().getGroup_3_3(), "rule__Class__Group_3_3__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_1(), "rule__Reference__Group_1__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_8(), "rule__Reference__Group_8__0");
			builder.put(grammarAccess.getGraphicAccess().getGroup(), "rule__Graphic__Group__0");
			builder.put(grammarAccess.getGraphicClassAccess().getGroup(), "rule__GraphicClass__Group__0");
			builder.put(grammarAccess.getVersionsAccess().getGroup(), "rule__Versions__Group__0");
			builder.put(grammarAccess.getVersionNameAccess().getGroup(), "rule__VersionName__Group__0");
			builder.put(grammarAccess.getConstraintsAccess().getGroup(), "rule__Constraints__Group__0");
			builder.put(grammarAccess.getPhysicsAccess().getGroup(), "rule__Physics__Group__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup(), "rule__PhysicClass__Group__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup_6(), "rule__PhysicClass__Group_6__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup_6_3(), "rule__PhysicClass__Group_6_3__0");
			builder.put(grammarAccess.getPhysicBodyAccess().getGroup(), "rule__PhysicBody__Group__0");
			builder.put(grammarAccess.getForcesAccess().getGroup(), "rule__Forces__Group__0");
			builder.put(grammarAccess.getForcesAccess().getGroup_4(), "rule__Forces__Group_4__0");
			builder.put(grammarAccess.getBitMasksAccess().getGroup(), "rule__BitMasks__Group__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup(), "rule__Gameloop__Group__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_14(), "rule__Gameloop__Group_14__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_14_3(), "rule__Gameloop__Group_14_3__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_15(), "rule__Gameloop__Group_15__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_15_3(), "rule__Gameloop__Group_15_3__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_16(), "rule__Gameloop__Group_16__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_17(), "rule__Gameloop__Group_17__0");
			builder.put(grammarAccess.getGameloopAccess().getGroup_17_3(), "rule__Gameloop__Group_17_3__0");
			builder.put(grammarAccess.getScoreAccess().getGroup(), "rule__Score__Group__0");
			builder.put(grammarAccess.getActionsAccess().getGroup(), "rule__Actions__Group__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_2(), "rule__Actions__Group_2__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_3(), "rule__Actions__Group_3__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_4(), "rule__Actions__Group_4__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_5(), "rule__Actions__Group_5__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_6(), "rule__Actions__Group_6__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_6_3(), "rule__Actions__Group_6_3__0");
			builder.put(grammarAccess.getCollisionsAccess().getGroup(), "rule__Collisions__Group__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup(), "rule__PhysicChanges__Group__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup_6(), "rule__PhysicChanges__Group_6__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup_7(), "rule__PhysicChanges__Group_7__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup_8(), "rule__PhysicChanges__Group_8__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup_9(), "rule__PhysicChanges__Group_9__0");
			builder.put(grammarAccess.getPhysicChangesAccess().getGroup_10(), "rule__PhysicChanges__Group_10__0");
			builder.put(grammarAccess.getGamePadAccess().getGroup(), "rule__GamePad__Group__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup(), "rule__ObjInit__Group__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_9(), "rule__ObjInit__Group_9__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_9_3(), "rule__ObjInit__Group_9_3__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getArithmeticAccess().getGroup(), "rule__Arithmetic__Group__0");
			builder.put(grammarAccess.getNotAccess().getGroup(), "rule__Not__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup(), "rule__Binary__Group__0");
			builder.put(grammarAccess.getAttributeValueAccess().getGroup(), "rule__AttributeValue__Group__0");
			builder.put(grammarAccess.getAllInstancesAccess().getGroup(), "rule__AllInstances__Group__0");
			builder.put(grammarAccess.getOntologicalAccess().getNameAssignment_1(), "rule__Ontological__NameAssignment_1");
			builder.put(grammarAccess.getOntologicalAccess().getURIAssignment_3_1(), "rule__Ontological__URIAssignment_3_1");
			builder.put(grammarAccess.getOntologicalAccess().getClassesAssignment_6(), "rule__Ontological__ClassesAssignment_6");
			builder.put(grammarAccess.getOntologicalAccess().getClassesAssignment_7_1(), "rule__Ontological__ClassesAssignment_7_1");
			builder.put(grammarAccess.getOntologicalAccess().getGraphicAssignment_10(), "rule__Ontological__GraphicAssignment_10");
			builder.put(grammarAccess.getOntologicalAccess().getPhysicAssignment_11(), "rule__Ontological__PhysicAssignment_11");
			builder.put(grammarAccess.getOntologicalAccess().getGameloopAssignment_12(), "rule__Ontological__GameloopAssignment_12");
			builder.put(grammarAccess.getClassAccess().getNameAssignment_0(), "rule__Class__NameAssignment_0");
			builder.put(grammarAccess.getClassAccess().getAttributesAssignment_2_0(), "rule__Class__AttributesAssignment_2_0");
			builder.put(grammarAccess.getClassAccess().getAttributesAssignment_2_1_1(), "rule__Class__AttributesAssignment_2_1_1");
			builder.put(grammarAccess.getClassAccess().getReferencesAssignment_3_2(), "rule__Class__ReferencesAssignment_3_2");
			builder.put(grammarAccess.getClassAccess().getReferencesAssignment_3_3_1(), "rule__Class__ReferencesAssignment_3_3_1");
			builder.put(grammarAccess.getClassAccess().getAbstractAssignment_5(), "rule__Class__AbstractAssignment_5");
			builder.put(grammarAccess.getClassAccess().getNoSCNAssignment_6(), "rule__Class__NoSCNAssignment_6");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
			builder.put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
			builder.put(grammarAccess.getAttributeAccess().getMinAssignment_4(), "rule__Attribute__MinAssignment_4");
			builder.put(grammarAccess.getAttributeAccess().getMaxAssignment_6(), "rule__Attribute__MaxAssignment_6");
			builder.put(grammarAccess.getAttributeAccess().getDefaultAssignment_9(), "rule__Attribute__DefaultAssignment_9");
			builder.put(grammarAccess.getAttributeAccess().getIsParamAssignment_10(), "rule__Attribute__IsParamAssignment_10");
			builder.put(grammarAccess.getAttributeAccess().getIsKeyAssignment_11(), "rule__Attribute__IsKeyAssignment_11");
			builder.put(grammarAccess.getAttributeAccess().getReadOnlyAssignment_12(), "rule__Attribute__ReadOnlyAssignment_12");
			builder.put(grammarAccess.getReferenceAccess().getNameAssignment_0(), "rule__Reference__NameAssignment_0");
			builder.put(grammarAccess.getReferenceAccess().getContaintmentAssignment_1_1(), "rule__Reference__ContaintmentAssignment_1_1");
			builder.put(grammarAccess.getReferenceAccess().getMinAssignment_3(), "rule__Reference__MinAssignment_3");
			builder.put(grammarAccess.getReferenceAccess().getMaxAssignment_5(), "rule__Reference__MaxAssignment_5");
			builder.put(grammarAccess.getReferenceAccess().getTargetAssignment_7(), "rule__Reference__TargetAssignment_7");
			builder.put(grammarAccess.getReferenceAccess().getOppositeAssignment_8_1(), "rule__Reference__OppositeAssignment_8_1");
			builder.put(grammarAccess.getGraphicAccess().getClassesAssignment_2(), "rule__Graphic__ClassesAssignment_2");
			builder.put(grammarAccess.getGraphicClassAccess().getOntoClassAssignment_1(), "rule__GraphicClass__OntoClassAssignment_1");
			builder.put(grammarAccess.getGraphicClassAccess().getVersionsAssignment_4(), "rule__GraphicClass__VersionsAssignment_4");
			builder.put(grammarAccess.getGraphicClassAccess().getVnameAssignment_8(), "rule__GraphicClass__VnameAssignment_8");
			builder.put(grammarAccess.getGraphicClassAccess().getConstraintsAssignment_12(), "rule__GraphicClass__ConstraintsAssignment_12");
			builder.put(grammarAccess.getVersionsAccess().getV1Assignment_2(), "rule__Versions__V1Assignment_2");
			builder.put(grammarAccess.getVersionsAccess().getV2Assignment_5(), "rule__Versions__V2Assignment_5");
			builder.put(grammarAccess.getVersionsAccess().getV3Assignment_8(), "rule__Versions__V3Assignment_8");
			builder.put(grammarAccess.getVersionNameAccess().getV1Assignment_2(), "rule__VersionName__V1Assignment_2");
			builder.put(grammarAccess.getVersionNameAccess().getV2Assignment_5(), "rule__VersionName__V2Assignment_5");
			builder.put(grammarAccess.getVersionNameAccess().getV3Assignment_8(), "rule__VersionName__V3Assignment_8");
			builder.put(grammarAccess.getConstraintsAccess().getPlanesAssignment_1(), "rule__Constraints__PlanesAssignment_1");
			builder.put(grammarAccess.getConstraintsAccess().getOverlappingAssignment_2(), "rule__Constraints__OverlappingAssignment_2");
			builder.put(grammarAccess.getConstraintsAccess().getSizeMinAssignment_4(), "rule__Constraints__SizeMinAssignment_4");
			builder.put(grammarAccess.getConstraintsAccess().getSizeMaxAssignment_6(), "rule__Constraints__SizeMaxAssignment_6");
			builder.put(grammarAccess.getConstraintsAccess().getXToOriginPosAssignment_8(), "rule__Constraints__XToOriginPosAssignment_8");
			builder.put(grammarAccess.getConstraintsAccess().getYToOriginPosAssignment_10(), "rule__Constraints__YToOriginPosAssignment_10");
			builder.put(grammarAccess.getConstraintsAccess().getZToOriginPosAssignment_12(), "rule__Constraints__ZToOriginPosAssignment_12");
			builder.put(grammarAccess.getConstraintsAccess().getRotationAssignment_14(), "rule__Constraints__RotationAssignment_14");
			builder.put(grammarAccess.getPhysicsAccess().getClassesAssignment_2(), "rule__Physics__ClassesAssignment_2");
			builder.put(grammarAccess.getPhysicClassAccess().getOntoClassAssignment_1(), "rule__PhysicClass__OntoClassAssignment_1");
			builder.put(grammarAccess.getPhysicClassAccess().getPhysicBodyAssignment_4(), "rule__PhysicClass__PhysicBodyAssignment_4");
			builder.put(grammarAccess.getPhysicClassAccess().getForcesAssignment_6_2(), "rule__PhysicClass__ForcesAssignment_6_2");
			builder.put(grammarAccess.getPhysicClassAccess().getForcesAssignment_6_3_1(), "rule__PhysicClass__ForcesAssignment_6_3_1");
			builder.put(grammarAccess.getPhysicClassAccess().getBitMasksAssignment_9(), "rule__PhysicClass__BitMasksAssignment_9");
			builder.put(grammarAccess.getPhysicBodyAccess().getMassAssignment_1(), "rule__PhysicBody__MassAssignment_1");
			builder.put(grammarAccess.getPhysicBodyAccess().getBodyTypeAssignment_3(), "rule__PhysicBody__BodyTypeAssignment_3");
			builder.put(grammarAccess.getPhysicBodyAccess().getChargeAssignment_5(), "rule__PhysicBody__ChargeAssignment_5");
			builder.put(grammarAccess.getPhysicBodyAccess().getFrictionAssignment_7(), "rule__PhysicBody__FrictionAssignment_7");
			builder.put(grammarAccess.getPhysicBodyAccess().getRollingFrictionAssignment_9(), "rule__PhysicBody__RollingFrictionAssignment_9");
			builder.put(grammarAccess.getPhysicBodyAccess().getRestitutionAssignment_11(), "rule__PhysicBody__RestitutionAssignment_11");
			builder.put(grammarAccess.getPhysicBodyAccess().getDampingAssignment_13(), "rule__PhysicBody__DampingAssignment_13");
			builder.put(grammarAccess.getPhysicBodyAccess().getAngularDampingAssignment_15(), "rule__PhysicBody__AngularDampingAssignment_15");
			builder.put(grammarAccess.getForcesAccess().getNameAssignment_0(), "rule__Forces__NameAssignment_0");
			builder.put(grammarAccess.getForcesAccess().getGestureAssignment_3(), "rule__Forces__GestureAssignment_3");
			builder.put(grammarAccess.getForcesAccess().getXVectorAssignment_4_1(), "rule__Forces__XVectorAssignment_4_1");
			builder.put(grammarAccess.getForcesAccess().getYVectorAssignment_4_3(), "rule__Forces__YVectorAssignment_4_3");
			builder.put(grammarAccess.getForcesAccess().getZVectorAssignment_4_5(), "rule__Forces__ZVectorAssignment_4_5");
			builder.put(grammarAccess.getBitMasksAccess().getCategoryAssignment_1(), "rule__BitMasks__CategoryAssignment_1");
			builder.put(grammarAccess.getBitMasksAccess().getCollisionAssignment_3(), "rule__BitMasks__CollisionAssignment_3");
			builder.put(grammarAccess.getBitMasksAccess().getContactTestAssignment_5(), "rule__BitMasks__ContactTestAssignment_5");
			builder.put(grammarAccess.getGameloopAccess().getStartAssignment_5(), "rule__Gameloop__StartAssignment_5");
			builder.put(grammarAccess.getGameloopAccess().getWinAssignment_7(), "rule__Gameloop__WinAssignment_7");
			builder.put(grammarAccess.getGameloopAccess().getLoseAssignment_9(), "rule__Gameloop__LoseAssignment_9");
			builder.put(grammarAccess.getGameloopAccess().getScoreAssignment_12(), "rule__Gameloop__ScoreAssignment_12");
			builder.put(grammarAccess.getGameloopAccess().getActionsTriggersAssignment_14_2(), "rule__Gameloop__ActionsTriggersAssignment_14_2");
			builder.put(grammarAccess.getGameloopAccess().getActionsTriggersAssignment_14_3_1(), "rule__Gameloop__ActionsTriggersAssignment_14_3_1");
			builder.put(grammarAccess.getGameloopAccess().getCollisionsAssignment_15_2(), "rule__Gameloop__CollisionsAssignment_15_2");
			builder.put(grammarAccess.getGameloopAccess().getCollisionsAssignment_15_3_1(), "rule__Gameloop__CollisionsAssignment_15_3_1");
			builder.put(grammarAccess.getGameloopAccess().getGamepadAssignment_16_2(), "rule__Gameloop__GamepadAssignment_16_2");
			builder.put(grammarAccess.getGameloopAccess().getObjInitAssignment_17_2(), "rule__Gameloop__ObjInitAssignment_17_2");
			builder.put(grammarAccess.getGameloopAccess().getObjInitAssignment_17_3_1(), "rule__Gameloop__ObjInitAssignment_17_3_1");
			builder.put(grammarAccess.getScoreAccess().getStartAssignment_1(), "rule__Score__StartAssignment_1");
			builder.put(grammarAccess.getScoreAccess().getFinishAssignment_3(), "rule__Score__FinishAssignment_3");
			builder.put(grammarAccess.getScoreAccess().getLivesAssignment_5(), "rule__Score__LivesAssignment_5");
			builder.put(grammarAccess.getActionsAccess().getNameAssignment_0(), "rule__Actions__NameAssignment_0");
			builder.put(grammarAccess.getActionsAccess().getActionAssignment_2_1(), "rule__Actions__ActionAssignment_2_1");
			builder.put(grammarAccess.getActionsAccess().getMessageAssignment_3_1(), "rule__Actions__MessageAssignment_3_1");
			builder.put(grammarAccess.getActionsAccess().getScoreChangeAssignment_4_1(), "rule__Actions__ScoreChangeAssignment_4_1");
			builder.put(grammarAccess.getActionsAccess().getTimeTriggerAssignment_5_1(), "rule__Actions__TimeTriggerAssignment_5_1");
			builder.put(grammarAccess.getActionsAccess().getPhysicChangesAssignment_6_2(), "rule__Actions__PhysicChangesAssignment_6_2");
			builder.put(grammarAccess.getActionsAccess().getPhysicChangesAssignment_6_3_1(), "rule__Actions__PhysicChangesAssignment_6_3_1");
			builder.put(grammarAccess.getCollisionsAccess().getClassAAssignment_1(), "rule__Collisions__ClassAAssignment_1");
			builder.put(grammarAccess.getCollisionsAccess().getClassBAssignment_3(), "rule__Collisions__ClassBAssignment_3");
			builder.put(grammarAccess.getCollisionsAccess().getActionAssignment_5(), "rule__Collisions__ActionAssignment_5");
			builder.put(grammarAccess.getPhysicChangesAccess().getActionAssignment_1(), "rule__PhysicChanges__ActionAssignment_1");
			builder.put(grammarAccess.getPhysicChangesAccess().getClassAssignment_3(), "rule__PhysicChanges__ClassAssignment_3");
			builder.put(grammarAccess.getPhysicChangesAccess().getObjectAssignment_5(), "rule__PhysicChanges__ObjectAssignment_5");
			builder.put(grammarAccess.getPhysicChangesAccess().getPositionAssignment_6_1(), "rule__PhysicChanges__PositionAssignment_6_1");
			builder.put(grammarAccess.getPhysicChangesAccess().getScaleAssignment_7_1(), "rule__PhysicChanges__ScaleAssignment_7_1");
			builder.put(grammarAccess.getPhysicChangesAccess().getAttributeAssignment_8_1(), "rule__PhysicChanges__AttributeAssignment_8_1");
			builder.put(grammarAccess.getPhysicChangesAccess().getChangeValueAssignment_9_1(), "rule__PhysicChanges__ChangeValueAssignment_9_1");
			builder.put(grammarAccess.getPhysicChangesAccess().getForceAssignment_10_1(), "rule__PhysicChanges__ForceAssignment_10_1");
			builder.put(grammarAccess.getGamePadAccess().getNameAssignment_0(), "rule__GamePad__NameAssignment_0");
			builder.put(grammarAccess.getGamePadAccess().getTriggerAssignment_2(), "rule__GamePad__TriggerAssignment_2");
			builder.put(grammarAccess.getObjInitAccess().getNameAssignment_0(), "rule__ObjInit__NameAssignment_0");
			builder.put(grammarAccess.getObjInitAccess().getClassAssignment_1(), "rule__ObjInit__ClassAssignment_1");
			builder.put(grammarAccess.getObjInitAccess().getPosXAssignment_3(), "rule__ObjInit__PosXAssignment_3");
			builder.put(grammarAccess.getObjInitAccess().getPosYAssignment_5(), "rule__ObjInit__PosYAssignment_5");
			builder.put(grammarAccess.getObjInitAccess().getPosZAssignment_7(), "rule__ObjInit__PosZAssignment_7");
			builder.put(grammarAccess.getObjInitAccess().getRulesAssignment_9_2(), "rule__ObjInit__RulesAssignment_9_2");
			builder.put(grammarAccess.getObjInitAccess().getRulesAssignment_9_3_1(), "rule__ObjInit__RulesAssignment_9_3_1");
			builder.put(grammarAccess.getRuleAccess().getActionAssignment_1(), "rule__Rule__ActionAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_3(), "rule__Rule__ConditionAssignment_3");
			builder.put(grammarAccess.getArithmeticAccess().getLeftAssignment_0(), "rule__Arithmetic__LeftAssignment_0");
			builder.put(grammarAccess.getArithmeticAccess().getOpAssignment_1(), "rule__Arithmetic__OpAssignment_1");
			builder.put(grammarAccess.getArithmeticAccess().getRightAssignment_2(), "rule__Arithmetic__RightAssignment_2");
			builder.put(grammarAccess.getNotAccess().getLeftAssignment_1(), "rule__Not__LeftAssignment_1");
			builder.put(grammarAccess.getBinaryAccess().getLeftAssignment_1(), "rule__Binary__LeftAssignment_1");
			builder.put(grammarAccess.getBinaryAccess().getOpAssignment_3(), "rule__Binary__OpAssignment_3");
			builder.put(grammarAccess.getBinaryAccess().getRightAssignment_5(), "rule__Binary__RightAssignment_5");
			builder.put(grammarAccess.getAttributeValueAccess().getClassAssignment_0(), "rule__AttributeValue__ClassAssignment_0");
			builder.put(grammarAccess.getAttributeValueAccess().getAttributeAssignment_2(), "rule__AttributeValue__AttributeAssignment_2");
			builder.put(grammarAccess.getConstantValueAccess().getValueAssignment(), "rule__ConstantValue__ValueAssignment");
			builder.put(grammarAccess.getAllInstancesAccess().getTypeAssignment_1(), "rule__AllInstances__TypeAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ArdslGrammarAccess grammarAccess;

	@Override
	protected InternalArdslParser createParser() {
		InternalArdslParser result = new InternalArdslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ArdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
