/*
 * generated by Xtext 2.28.0
 */
package ardsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArdslScopeProvider extends DelegatingScopeProvider {
}
