/*
 * generated by Xtext 2.33.0
 */
package arg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArgScopeProvider extends DelegatingScopeProvider {
}
